apiVersion: v1
kind: BuildConfig
metadata:
  name: spark-2.4.2
spec:
  source:
    git:
        uri: "https://github.com/wrenkredhat/openshift-spark"
        ref: "master"
    type: Git
  strategy:
    dockerStrategy:
      noCache: true
  output:
    to:
      kind: ImageStreamTag
      name: spark:2.4.2
