apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: spark-jumper
spec:
  replicas: 1
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        name: spark-jumper
    spec:
      containers:
      - image: docker-registry.default.svc:5000/spark/spark:2.4.2
        name: spark-jumper
        args:
          - 'jumper'
        resources: {}
        serviceAccount: siab
        serviceAccountName: siab
        restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - spark-jumper
      from:
        kind: ImageStreamTag
        name: spark:2.4.2
    type: ImageChange
