apiVersion: v1
kind: Service
metadata:
  name: spark-jumper
  labels:
    name: spark-jumper
spec:
  ports:
  - name: jumper
    port: 8085
    protocol: TCP
    targetPort: 8080
  selector:
    name: spark-jumper
